language: java
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
before_install:
- mkdir -p ~/.m2
install:
  - mvn clean package -DskipTests
deploy:
  provider: releases
  api_key:
    secure: "A5iOSNFZ2+rjTpjo2aahDiAo8oXuYOzq3nEZkl5wzF51k5iihbY9BIY/xuOgVf36lQRrsDQSbDZ3SCcprOYQSgZ6yd+/3oHuFeuKDa+yGlwzHHFVCMU0le8Qkup9RGrzAdsmE5QFPuDLMzjC8yK4m7hOoSgGy+y+Adtu4oySLIHkRo/duXzVThcV5Gtl6V7I8aHt18GIkG7RHiEPgA8LLcBNGoVW5yuAEJAn9QXr2y3nxUHj3JG1E1M+zqYcGR+yFQx6OiFPZu9KBHgVDTtj8dAD62BC0jqrEqmFOIHdO5Mrsx/OX1WG8AR+WtO1d+AyNFw6l2/ep8K30YhFwehJQSgNhbcS6w1PqYcu1j0AnlOGvRDtiKn3nb4hESdxhUqF50V2VrLon3JRp2m8U60D38RREdS0HxO2p0J7z2sFjlIphDSpFoBpJLLLOBLTOGDTO3tAlK66mg1b+R1pxIlb/odMa3Q2dr1u/4rvrCECU40S1krn9lkAQL6YL8rJ64BCOtiDtOefgbfvOxLNuxybHhOflrxjWnU9XcL7fvKYdmyhcHlH4GixwnwDxU0LMBdhEwrHhsYBAnpsp/0HpU0M4HY4qhiocu/onsMI9geueNVB2PAXy2DHnrpAlq1zEFb5Z2bznrXW7NQkV6e7bWfaDbkGOCdJ0kbZxR9oZIfESWU="
  file: "./target/cas-exec.war"
  cleanup: true
  file_glob: true
  overwrite: true
  on:
    repo: bioatlas/ala-cas-5
    tags: true
    all-branches: true
